version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: tempfetcher
    ports:
      - "8080:8080"
    volumes:
      - ./config.yml:/app/config.yml
    command: ["-c", "/app/config.yml"]
    environment:
      - OWM_API_KEY=${OWM_API_KEY}
    networks:
      - otel-network

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - otel-network

networks:
  otel-network:
    driver: bridge 