version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: tempfetcher
    ports:
      - "8080:8080"
    volumes:
      - ./config.yml:/app/config.yml
    command: ["-c", "/app/config.yml"]
    environment:
      - OWM_API_KEY=${OWM_API_KEY}
      - OTEL_EXPORTER_OTLP_ENDPOINT=jaeger:4318
    networks:
      - otel-network

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - otel-network

  jaeger:
    image: jaegertracing/all-in-one:1.54  # Updated to v2 (1.54.0)
    ports:
      - "16686:16686"  # Web UI
      - "4318:4318"    # OTLP HTTP receiver
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    networks:
      - otel-network

networks:
  otel-network:
    driver: bridge 